import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-bg-image bg-cover bg-center min-h-screen">
      <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  )
}
